#%RAML 1.0
title: riding' dirty
version: 1
description: Ridin' Dirty API
baseUri: https://ridindirtyatl-api.herokuapp.com/v{version}
mediaType: application/json

types:
  Bus:
    type: object
    properties:
      vehicle_id:
        type: integer
      route_id:
        type: integer
      destination:
        type: string
      adherence:
        type: integer
      prev_stop:
        type: string
      next_stop:
        type: string
      actual_passenger_count:
        type: integer
  Route:
    type: object
    properties:
      vehicle_list:
        type: integer[]
  Aggregates:
    type: object
    properties:
      avg_passenger_count:
        type: integer
      max_passenger_count:
        type: integer
      min_passenger_count:
        type: integer
      avg_adherence_count:
        type: integer
      max_adherence_count:
        type: integer
      min_adherence_count:
        type: integer
  Timestamp:
    description: |
      A restricted ISO 8601 timestamp
        * Second resolution only.
        * UTC only using the 'Z' notation.
    type: string
    pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$
    example: '2016-08-24T23:59:ddZ'
/bus:
  /{id}:
    uriParameters:
      id:
        type: integer
    get:
      description: Get information about a single bus
      queryParameters:
        start:
          type: Timestamp
          required: false
        end:
          type: Timestamp
          required: false
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                bus:
                  type: Bus
                aggregates:
                  type: Aggregates
/buses:
  get:
    description: Get a list of all buses
    queryParameters:
      start_time:
        type: Timestamp
        required: false
      end_time:
        type: Timestamp
        required: false
      route_id:
        type: integer
        required: false
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              routes:
                type: Bus[]
              aggregates:
                 type: Aggregates
/route/{id}:
    uriParameters:
      id:
        type: integer
    get:
      description: Get information about a single route
      queryParameters:
        start:
          type: Timestamp
          required: false
        end:
          type: Timestamp
          required: false
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                route:
                  type: Route
                aggregates:
                  type: Aggregates
/routes:
  get:
    description: Get a list of routes
    queryParameters:
      start_time:
        type: Timestamp
        required: false
      end_time:
        type: Timestamp
        required: false
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              routes:
                type: Route[]
              aggregates:
                 type: Aggregates
